apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shelfwatch.fullname" . }}-config
  labels:
    {{- include "shelfwatch.labels" . | nindent 4 }}
data:
  WEIGHTS_PATH: {{ .Values.config.weightsPath | quote }}
  CONF_THRESH: {{ .Values.config.confThresh | quote }}
  IMG_SIZE: {{ .Values.config.imgSize | quote }}
  MODEL_NAME: {{ .Values.config.modelName | quote }}
