apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shelfwatch.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "shelfwatch.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: shelfwatch-grafana
                port:
                  number: 80
